# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

# https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/

image: atlassian/default-image:3

pipelines:
  tags:
    '*':

    # --------------------------------------------------------
    # If you want to manually deploy enable the following step and
    # make the next step trigger 'manual'.
    # --------------------------------------------------------
    # - step:
    #     name: 'Intialize'
    #     script:
    #       - echo "Hello from WordPress plugin pipeline."

    - step:
        name: Deploy to S3
        # See above.
        # trigger: manual
        script:
          # Install the zip utility.
          - apt-get install zip

          # Copy the required files to the plugin_name folder
          - mkdir plugin_name

          # Add other folders here.
          - cp -r inc plugin_name

          # Add other files here.
          - cp bb2s3.php plugin_name
          - cp README.md plugin_name

          # Zip the copied files.
          - zip -r plugin_name.zip plugin_name 

          # Add the updated JSON file and other files.
          - mkdir download
          - mv plugin_name.zip download
          - cp info.json download

          # sync your files to S3
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: 'rangequest'
              LOCAL_PATH: 'download'

          # triggering a distribution invalidation to refresh the CDN caches
          # - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
          #   variables:
          #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          #     AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          #     DISTRIBUTION_ID: '123xyz'